name: Build Flutter Apps

on:
  workflow_dispatch:

jobs:
  build-android:
    name: 🎉 Android Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get

      - run: flutter build apk --release --split-per-abi

      - name: Verify APK
        run: ls -l build/app/outputs/apk/release/

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-release
          path: build/app/outputs/apk/release/*

  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      - name: Update CocoaPods Repository
        run: pod repo update
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - run: zip -qq -r -9 hocFlutter.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Verify IPA
        run: ls -l build/ios/iphoneos/

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ipa-release
          path: build/ios/iphoneos/hocFlutter.ipa

  release:
    name: 🎉 Publish Release
    needs: [build-android, build-ios]
    runs-on: ubuntu-22.04
    steps:
      - name: Download APK Artifact
        uses: actions/download-artifact@v3
        with:
          name: apk-release

      - name: Download IPA Artifact
        uses: actions/download-artifact@v3
        with:
          name: ipa-release

      - name: Publish to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/apk/release/*
            build/ios/iphoneos/hocFlutter.ipa
          tag: v1.0
          token: ${{ secrets.TOKEN }}
          body: "Học Flutter Cùng Tuancute"